### ISSUE TITLE
request: for config file

### ISSUE THREAD

**Issue by Surpos0** [alessandrv/alessandrv-enchantments#1]
It would be great to chose what enchants i want to have in game.

**Comment by alessandrv** [comment]
> It would be great to chose what enchants i want to have in game.

Support has already been implemented, not sure what version you are using but after the added dependency for cloth config api the mod uses a config file to tweak all enchantments, even via mod menu!
Try it out and let me know, you can download the latest version here: https://modrinth.com/mod/alessandrv-enchantments

**Comment by Surpos0** [comment]
thx, you were right i was having older version, sorry for bothering.
