### ISSUE TITLE
Bone Meal only works in Creative

### ISSUE THREAD

**Issue by BlueIsADude** [alessandrv/alessandrv-enchantments#14]
Testing out the mod for a server, i noticed that Bone Meal doesn't work in survival mode. When trying to use it in survival, it causes the villager anger particles to show up, and does nothing. It works perfectly fine in creative though, but it has no cooldown there.

![image](https://github.com/alessandrv/alessandrv-enchantments/assets/159506207/de8a54a6-e1cf-4c16-a77b-bb253e9908d8)
Me using a Bone Meal hoe in survival

![image](https://github.com/alessandrv/alessandrv-enchantments/assets/159506207/6b7b2321-eb4d-4baf-a5af-36758dfb935f)
Me using it again, but in creative

**Comment by alessandrv** [comment]
Hello, you Need to have bone meal in your inventory for it to work in
survival (to balance it out).

**Comment by BlueIsADude** [comment]
ohhhhhhhhh ok
that makes sense lol, but maybe you could specify that in the enchantment description?
