### ISSUE TITLE
Crash when using Voidless enchantment without set spawnpoint

### ISSUE THREAD

**Issue by TheTrueYak** [alessandrv/alessandrv-enchantments#2]
I was testing enchantments and when applying Voidless to a full set of diamond armor and falling into the void beneath the overworld, the game crashed. Upon reviewing the crash report, it was due to a NullPointerException because spawnPos was null. A spawnpoint had never been set for the player on this world, so that's probably why. Attached is the crash report.

Version: 1.4.5

Expected outcome: Player is teleported to the world spawn if no spawnpoint has been set.

Actual outcome: Game crashes due to NullPointerException

[crash-2023-09-02_17.10.26-server.txt](https://github.com/alessandrv/alessandrv-enchantments/files/12504822/crash-2023-09-02_17.10.26-server.txt)

**Comment by alessandrv** [comment]
Fixed with last update
