### ISSUE TITLE
crash when swinging at a zombie

### ISSUE THREAD

**Issue by memphismc** [alessandrv/alessandrv-enchantments#8]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2023-12-05 21:20:02
Description: Unexpected error

java.lang.ClassCastException: class net.minecraft.class_638 cannot be cast to class net.minecraft.class_3218 (net.minecraft.class_638 and net.minecraft.class_3218 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @589b3632)
	at com.alessandrv.alessandrvenchantments.enchantments.VampiricEnchantment.method_8189(VampiricEnchantment.java:67)
	at net.minecraft.class_1890.method_8207(class_1890.java:179)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8213(class_1890.java:181)
	at net.minecraft.class_1657.method_7324(class_1657.java:1342)
	at net.minecraft.class_310.performAttack(class_310.java:6811)
	at net.minecraft.class_310.attackFromUpswingIfNeeded(class_310.java:6698)
	at net.minecraft.class_310.handler$zkn000$bettercombat$pre_Tick(class_310.java:6756)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.alessandrv.alessandrvenchantments.enchantments.VampiricEnchantment.method_8189(VampiricEnchantment.java:67)
	at net.minecraft.class_1890.method_8207(class_1890.java:179)
	at net.minecraft.class_1890.method_17883(class_1890.java:138)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1890.method_8220(class_1890.java:138)
	at net.minecraft.class_1890.method_8209(class_1890.java:144)
	at net.minecraft.class_1890.method_8213(class_1890.java:181)
	at net.minecraft.class_1657.method_7324(class_1657.java:1342)
	at net.minecraft.class_310.performAttack(class_310.java:6811)
	at net.minecraft.class_310.attackFromUpswingIfNeeded(class_310.java:6698)
	at net.minecraft.class_310.handler$zkn000$bettercombat$pre_Tick(class_310.java:6756)

-- Affected level --
Details:
	All players: 1 total; [class_746['mataicurva'/1, l='ClientLevel', x=1725.42, y=-12.00, z=1520.99]]
	Chunk stats: 1024, 396
	Level dimension: minecraft:overworld
	Level spawn location: World: (-64,66,48), Section: (at 0,2,0 in -4,4,3; chunk contains blocks -64,-64,48 to -49,319,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 296592 game time, 346794 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, loadmyresources.hiddenpack, continuity/default, minecraft/physicsmod, continuity/glass_pane_culling_fix, EclecticTrove-noconfig-1.19-1.2.0.zip, Pixelated_v1.3.1_EnhancedVisuals(nox_cgt).zip, Repurposed_Structures-Friends_And_Foes_v3.zip, cubic-sun-moon-v1-6-1.zip, 2D Weapon Models, Seasonal Lush Caves, CaveDweller_SoundOverhaul.zip, Dubious_Dweller.zip, More Cave Sounds.zip

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 977670712 bytes (932 MiB) / 2315255808 bytes (2208 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 58 Stepping 9
	Microarchitecture: Ivy Bridge (Client)
	Frequency (GHz): 3.39
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=31.0.15.4629
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Virtual memory max (MB): 14540.18
	Virtual memory used (MB): 11047.61
	Swap memory total (MB): 6400.00
	Swap memory used (MB): 440.12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced-tooltips: Advanced Tooltips 1.6.0+1.19
			advanced-tooltips-core: Advanced Tooltips Core 1.6.0
		advdebug: Advancements Debug 2.3.0
		alessandrvenchantments: Alessandrv's Enchantments 1.5.1
		alloy_forgery: Alloy Forgery 2.1.1+1.19
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		animatica: Animatica 0.5+1.19
		apollo: Apollo's Additional Structures 1.3.3
		architectury: Architectury 6.5.85
		armorpointspp: Armorpoints++ 3.1.0
			fiber: fiber 0.23.0-2
		auditory: Auditory 0.0.4-1.19.x
		autotag-convention: AutoTag Convention 2.0.0+1.19
			autotag: AutoTag 2.0.0+1.19
		awesomedungeon: Awesome dungeon 3.2.0
		awesomedungeonend: Awesome dungeon the end 3.1.1
		awesomedungeonnether: Awesome dungeon nether 3.1.1
		awesomedungeonocean: Awesome dungeon edition ocean 3.2.0
		badpackets: Bad Packets 0.2.3
		bclib: BCLib 2.1.7
		bedrodium: Bedrodium 0.2
		bettercombat: Better Combat 1.7.1+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterend: Better End 2.1.6
		betterendisland: YUNG's Better End Island 1.19.2-Fabric-1.0
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.6
		betterfpsdist: Better FPS distance Mod 1.19-2.4
		betterjungletemples: YUNG's Better Jungle Temples 1.19.2-Fabric-1.0.1
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.1
		betternether: Better Nether 7.1.4
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.1
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		blanket-client-tweaks: Blanket Client-tweaks 1.1.2
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.3.20
		byg: Oh The Biomes You'll Go 2.0.1.6
		cameraoverhaul: Camera Overhaul 1.4.0-fabric-universal
		cave_dweller: Cave Dweller Fabric 1.3.0
		cavedust: Cave Dust 1.2.0
		caveore: Cave Spelunking 1.19-2.4
		cem: Custom Entity Models 0.7.1_S7_1.19
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charm_fixer: Charm Fixer 1.0.0
		choicetheorems_overhauledvillagefriendsandfoesaddon_mr: ChoiceTheorem's Overhauled Village - Friends and Foes Add-on 1.1
		chunky: Chunky 1.3.38
		citresewn: CIT Resewn 1.1.2+1.19.2
			citresewn-defaults: CIT Resewn: Defaults 1.1.2+1.19.2
		cloth-config: Cloth Config v8 8.3.103
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.11
		colormatic: Colormatic 3.1.2+mc.1.19
		continuity: Continuity 2.0.2+1.19
		controlling: Controlling For Fabric 10.0+7
		corgilib: CorgiLib 1.0.0.34
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
		cr-arrows-info: Arrows Info 1.2.2+1.19
		creativecore: CreativeCore (Fabric) 2.9.3
		criticalib: CriticaLib 1.0.0
		crosshairmod: Crosshair Mod 0.5.0
		ctov: ChoiceTheorem's Overhauled Village 3.2.5
		ctov_morevillagerscompat_mr: ChoiceTheorem's Overhauled Village - More villagers add-on 1.1
		damagetilt: Damage Tilt 1.19-fabric-0.1.2
		dataattributes: Data Attributes 1.4.6+1.19.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.8.0
		deeperdarker: Deeper and Darker 1.2.3
			customportalapi: Custom Portal Api 0.0.1-beta63-1.19.X
		dsurround: Dynamic Surroundings: Remastered Fabric Edition 0.1.1
			org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		duckling: Duckling 2.0.8
		dungeons_andtaverns_mr: Dungeons and Taverns 2.0.2
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		easierenchanting: Easier Enchanting 1.5.0
		easyshulkerboxes: Easy Shulker Boxes 4.4.1
		effective: Effective 1.4
		elytraslot: Elytra Slot 6.1.1+1.19.2
		enchantment-numbers-fix: Enchantment Numbers Fix 1.0.0
		enchdesc: EnchantmentDescriptions 13.0.14
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.4+1.19
		enhancedcelestials: Enhanced Celestials 2.1.0.6
		enhancedvisuals: Enhanced Visuals (Fabric) 1.5.9
		entity_texture_features: Entity Texture Features 4.6.1
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entitycollisionfpsfix: Entity Collision FPS Fix 2.0.0.0
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		equipmentcompare: Equipment Compare 1.3.1
		expandedironbundles: Expanded Iron Bundles 0.0.3+mc1.19-fabric
		explorations: Explorations 1.19.2-1.5.2
		explorify-fabric: Explorify 1.19-1.3.0
		explosiveenhancement: Explosive Enhancement 1.2.2-1.19.2
		expore: Exp Ore 1.0
		fabric-api: Fabric API 0.77.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.1.0+ee641e7390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.25+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.28+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+526f2c6790
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricenchantments: Fabric Enchantments 0.9.0
		fabricloader: Fabric Loader 0.14.24
		fabricshieldlib: Fabric Shield Lib 1.7.2-1.19.2
			mm: Manningham Mills 2.3
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		ferritecore: FerriteCore 5.0.3
		firstperson: FirstpersonModel 2.2.3
		forgeconfigapiport: Forge Config API Port 4.2.11
		friendsandfoes: Friends&Foes 2.0.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.1
		frycmobvariants: Mob Variants 1.2.2+1.19.2
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		geodes: More Geodes 1.7+1.19
		giantspawn: Giant Spawn 4.7
		globaldataandresourcepacks: Global Data- & Resourcepacks 1.14.5_fabric
		grindenchantments: Grind Enchantments 3.1.1+1.19.2
			codec-config-api: Codec Config API 1.0.2+1.19.3
		held-item-info: Held Item Info 1.4.0
		iceberg: Iceberg 1.0.46
		illuminations: Illuminations 1.10.11
		immediatelyfast: ImmediatelyFast 1.2.7+1.19.2
			net_lenni0451_reflect: Reflect 1.3.0
		improvedmobs: Improved Mobs 1.19-1.11.0
		imst: Immersive structures 2.0.7a
		imst_n: Immersive Structures:Nether edition 1.0.0
		indium: Indium 1.0.9+mc1.19.2
		iris: Iris 1.6.10
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		itemborders: Item Borders 1.1.6
		jamlib: JamLib 0.6.1+1.19-1.19.2
		java: OpenJDK 64-Bit Server VM 17
		jumpyboat: JumpyBoat 4.0-1.19
		kiwi: Kiwi Lib 8.3.3
		knavesneeds: Knaves' Needs 1.1.5.1+1.19.2
		konkrete: Konkrete 1.6.1
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		leaf-decay: Leaf Decay 1.5.0-1.19.2
		leavemybarsalone: Leave My Bars Alone 4.0.0
		legendarytooltips: Legendary Tooltips 1.3.3
		libipn: libIPN 4.0.1
		libraryferret: Library ferret 4.0.0
		libz: LibZ 1.0.0
		linearxp: Linear XP 1.0.1
		lithium: Lithium 0.11.1
		loadmyresources: Load My Resources 1.0.4
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.0-1.19
		malilib: MaLiLib 0.13.0
		mambience: MAmbience 5.2.0+1.19
		mc249136: MC-249136 (Fabric) 1.0.1
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		minecraft_legends: Minecraft Legends Mod 1.19.2-0.2.1
		modernfix: ModernFix 5.10.0+mc1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		moonlight: Moonlight 1.19.2-2.3.5
		mooshroomspawn: Mooshroom Spawn 3.4
		mooshroomtweaks: Mooshroom Tweaks 3.3
		more_babies: More Babies 1.0.0
		moreculling: More Culling 1.19.1-0.17.0
		morecullingextra: More Culling Extra 1.1-backport_1.19.2
		moremobvariants: More Mob Variants 1.0.1
		moreuniqueblackstone: More Unique Blackstone 1.0.0-1.19-1.19.2
		morevillagers: More Villagers 4.0.2
		morezombievillagers: More Zombie Villagers 3.4
		mostructures: Mo' Structures 1.4.3+1.19.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		mru: Mineblock's Repetition Utilities 0.1.5+1.19.2
			com_sksamuel_scrimage_scrimage-core: scrimage-core 4.0.31
		mvs: Moog's Voyager Structures 4.1-1.19.2-fabric
		mythicmetals: Mythic Metals 0.17.3+1.19.2
			additionalentityattributes: Additionalentityattributes 1.2.0+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		naturallychargedcreepers: Naturally Charged Creepers 3.3
		nbtcrafting: NBT Crafting 2.2.3+mc1.19
		nethermooshrooms: NetherMooshrooms 1.1
		nethersheep: NetherSheep 1.6
		noenchantcap: No Enchant Cap 2.2.4
		notenoughanimations: NotEnoughAnimations 1.6.4
		optigui: OptiGUI 2.1.6
			optiglue: OptiGlue 2.1.6-mc.1.19
			org_apache_commons_commons-text: commons-text 1.10.0
			org_ini4j_ini4j: ini4j 0.5.4
		overenchanted: Over Enchanted 1.2.0
		overworldnetheriteoremodfabric: Overworld Netherite Mod Fabric 1.5
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		particlerain: Particle Rain 2.0.0
		physicsmod: Physics Mod 2.12.4
		pickupnotifier: Pick Up Notifier 4.2.4
		player-animator: Player Animator 1.0.2
		playerex: PlayerEx 3.5.4+1.19.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.4
			placeholder-api: Placeholder API 2.0.0-pre.1+1.19.2
			projectile_damage: Projectile Damage Attribute 3.2.1+1.19
		presencefootsteps: Presence Footsteps 1.6.4
			kirin: Kirin UI 1.11.1
		prism: Prism 1.0.3
		puzzle: Puzzle 1.4.2-1.19
			puzzle-base: Puzzle Base 1.4.2-1.19
			puzzle-gui: Puzzle GUI 1.4.2-1.19
			puzzle-models: Puzzle Models 1.4.2-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.2-1.19
		puzzleslib: Puzzles Lib 4.4.3
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		rainglow: Rainglow 1.0.0+mc1.19.2
		rayon: Rayon 1.7.1+1.19.2
			toolbox: Lazurite Toolbox 1.4.0+1.19.2
			transporter: Transporter 1.4.0+1.19.2
		realisticbees: Realistic Bees 3.5
		reeses-sodium-options: Reese's Sodium Options 1.6.4+mc1.19.2-build.93
		relicex: RelicEx 3.3.2+1.19.2
			armorrenderlib: Armor Render Lib 0.2.6
		repurposed_structures: Repurposed Structures 6.3.28+1.19.2
		rottencreatures: Rotten Creatures 1.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.668
			error_notifier: Error Notifier 1.0.9
		screenshotclipboard: Screenshot to Clipboard 1.0.9
		seasons: Fabric Seasons 2.3+1.19
		seasonsbygcompat: Fabric Seasons: BYG Compat 1.0-2.0.1.1
		seasonsterraformerscompat: Fabric Seasons: Terraformers Compat 1.0
		shouldersurfing: Shoulder Surfing Reloaded 2.3.0
		simplyswords: Simply Swords 1.43.1-1.19.2
		skeletonhorsespawn: Skeleton Horse Spawn 3.7
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.9.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.16+mc1.19.2-build.90
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		soulfired: Soul fire'd 3.1.0.0-final
		soulsweapons: Marium's Soulslike Weaponry 0.9.9.3
		spellbound: Spellbound 1.14.0.1
			modify-drops-api: Modify Drops API 0.4.0.2
		starlight: Starlight 1.1.1+fabric.ae22326
		strayspawn: Stray Spawn 3.4
		structory: Structory 1.3.1a
		stylisheffects: Stylish Effects 4.3.4
		subterrestrial: Subterrestrial 2.0.0
		t_and_t: Towns and Towers 1.10
		takesapillage: Takes a Pillage 1.0.4
		tenshilib: TenshiLib 1.19.2-1.6.15
		terrablender: TerraBlender 2.0.1.166
		tia: Tiny Item Animations 1.19.2-1.0.0
		tlc: The Lost Castle 1.0.0
		toolstats: ToolStats 12.1.4
		tooltipfix: ToolTip Fix 1.1.1-1.19
		tooltipscroller: Tooltip Texts Scroller 1.0.0
		tooltiptweaks: Tooltip Tweaks 1.1.0
		treechop: HT's TreeChop 0.17.6
		trinkets: Trinkets 3.4.2
		tumbleweed: Tumbleweed 0.5.1
		universal_ores: Universal Ores 1.4.2
		universalenchants: Universal Enchants 4.2.15
			extensibleenums: Extensible Enums 4.0.0
		veinmining: Vein Mining 1.1.3+1.19.2
			spectrelib: SpectreLib 0.12.6+1.19.2
		villagerarmor: Villager Armor Layer 4.0.0
		villagers-follow-emeralds: Villagers Follow Emeralds 1.3.0
		visuality: Visuality 0.5.6
		wthit: wthit 5.19.3
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yosbr: YOSBR 0.1.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.10
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
		zombiehorsespawn: Zombie Horse Spawn 4.7
		zombievillagersfromspawner: Zombie Villagers From Spawner 3.6
		zoomify: Zoomify 2.9.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.5
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.5
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.5
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.5
	Loaded Shaderpack: Sildur's+Enhanced+Default+v1.16+Fancy.zip
		Profile: Custom (+7 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.24-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 546.29, NVIDIA Corporation
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, loadmyresources.hiddenpack (incompatible), continuity/default, minecraft/physicsmod, continuity/glass_pane_culling_fix, file/EclecticTrove-noconfig-1.19-1.2.0.zip, file/Pixelated_v1.3.1_EnhancedVisuals(nox_cgt).zip (incompatible), file/Repurposed_Structures-Friends_And_Foes_v3.zip (incompatible), file/cubic-sun-moon-v1-6-1.zip (incompatible), 2D Weapon Models, Seasonal Lush Caves, file/CaveDweller_SoundOverhaul.zip, file/Dubious_Dweller.zip (incompatible), file/More Cave Sounds.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['mataicurva'/1, l='ServerLevel[New World]', x=1725.42, y=-12.00, z=1520.99]]
	Data Packs: vanilla, Fabric Mods, global:Repurposed_Structures-Friends_And_Foes_v3.zip, loadmyresources.hiddenpack (incompatible)
	World Generation: Stable

**Comment by Slayer5934** [comment]
As stated in the crash report, it seems to be the Vampiric Enchantment causing the issue.

**Comment by alessandrv** [comment]
Sorry for the late fix, busy with uni.

**Comment by memphismc** [comment]
> Sorry for the late fix, busy with uni.

don't worry, already uninstalled this mod, keep having one too many crashes with it

including this [https://pastebin.com/yxXz8mAX]

**Comment by alessandrv** [comment]
> > Sorry for the late fix, busy with uni.
> 
> don't worry, already uninstalled this mod, keep having one too many crashes with it
> 
> including this [https://pastebin.com/yxXz8mAX]

Sorry to hear that,  unfortunately I been really busy and before stopping the developing I tried to implement a system to avoid cheesing the cooldowns of the strong enchantments which caused a lot of crashes that I just fixed removing that.

**Comment by Slayer5934** [comment]
I am glad you could get some time to fix it, thank you! <3 I hope your uni stuff is going well
-------- Original Message --------

**Comment by Slayer5934** [comment]
Any plans to backport to 1.19.2 @alessandrv ? if not i could fork it and try i suppose o.o
